More promising error but still not closer. Going to bed!
root cause

org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: com.planit.persistence.mapping.eventUsers.pk.PlanitEvent in com.planit.persistence.events.PlanitEvent.attendees